#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include "wiki_zim.h"
#include "html_text.h"

// Two dataset backends live side by side under /sdcard/wiki/:
//
//   /sdcard/wiki/<slug>/meta.json     { "name", "description", "language" }
//   /sdcard/wiki/<slug>/index.bin     sorted array of on-disk records
//   /sdcard/wiki/<slug>/articles.dat  concatenated raw article bodies (UTF-8)
//     -- generated by tools/wiki_pack.py; index.bin is sorted by
//        lowercase(title) so lookups binary-search it directly from the SD
//        card without loading it into RAM.
//
//   /sdcard/wiki/<name>.zim           a Kiwix ZIM file copied to the SD card
//     -- read directly with wiki_zim.h; HTML bodies are converted to plain
//        text with html_text.h at load time.

#define WIKI_TITLE_MAX         96
#define WIKI_SLUG_MAX          64
#define WIKI_NAME_MAX          64
#define WIKI_DESC_MAX          160
#define WIKI_MAX_DATASETS      16
#define WIKI_MAX_RESULTS       14
#define WIKI_ARTICLE_MAX_BYTES (96 * 1024)

typedef enum {
    WIKI_BACKEND_FLAT,  // tools/wiki_pack.py output folder
    WIKI_BACKEND_ZIM,   // a .zim file
} wiki_backend_t;

typedef struct {
    char           slug[WIKI_SLUG_MAX];
    char           name[WIKI_NAME_MAX];
    char           description[WIKI_DESC_MAX];
    char           language[8];
    uint32_t       article_count;
    wiki_backend_t backend;
} wiki_dataset_info_t;

typedef struct {
    wiki_dataset_info_t info;
    FILE                *index_file;     // WIKI_BACKEND_FLAT
    FILE                *articles_file;  // WIKI_BACKEND_FLAT
    zim_archive_t        zim;            // WIKI_BACKEND_ZIM
} wiki_dataset_t;

// A single search result / article handle. Opaque to callers other than
// wiki.c -- always go through wiki_result_title() rather than reading
// fields directly.
typedef struct {
    char title[WIKI_TITLE_MAX + 1];
    union {
        struct {
            uint32_t offset;
            uint32_t length;
        } flat;
        struct {
            uint32_t entry_index;
        } zim;
    };
} wiki_result_t;

typedef struct {
    char             *text;
    size_t            len;
    html_text_link_t links[HTML_TEXT_MAX_LINKS];
    size_t            link_count;
} wiki_article_t;

static inline const char *wiki_result_title(const wiki_result_t *r) {
    return r->title;
}

// Scans /sdcard/wiki for dataset folders (tools/wiki_pack.py output) and
// *.zim files, filling `out` with up to `max_out` entries. Returns the
// number found.
size_t wiki_discover_datasets(wiki_dataset_info_t *out, size_t max_out);

// Opens a dataset previously returned by wiki_discover_datasets(). Returns
// false on failure.
bool wiki_dataset_open(const wiki_dataset_info_t *info, wiki_dataset_t *ds);

// Closes whatever file handles wiki_dataset_open() opened.
void wiki_dataset_close(wiki_dataset_t *ds);

// Finds up to `max_out` results whose title starts with `prefix`, skipping
// the first `skip` matches. Pass an empty prefix to browse the whole
// dataset alphabetically. Returns the number of results written to `out`,
// and whether more matches exist after them in *out_has_more.
size_t wiki_search_prefix(
    wiki_dataset_t *ds, const char *prefix, size_t skip, wiki_result_t *out, size_t max_out, bool *out_has_more
);

// Loads an article's body as plain text into a newly malloc'd,
// NUL-terminated buffer. Caller must free() *out_text. Bodies larger than
// WIKI_ARTICLE_MAX_BYTES are truncated.
bool wiki_load_article(wiki_dataset_t *ds, const wiki_result_t *result, char **out_text, size_t *out_len);

bool wiki_load_article_ex(wiki_dataset_t *ds, const wiki_result_t *result, wiki_article_t *out);

void wiki_article_free(wiki_article_t *article);

bool wiki_dataset_main_page(wiki_dataset_t *ds, wiki_result_t *out);

bool wiki_dataset_random_article(wiki_dataset_t *ds, uint32_t seed, wiki_result_t *out);

bool wiki_result_from_zim_path(wiki_dataset_t *ds, const wiki_result_t *current, const char *href, wiki_result_t *out);
